### ISSUE TITLE
Need to use PDO::ATTR_EMULATE_PREPARES

### ISSUE THREAD

**Issue by pokmot** [atlasphp/Atlas.Symfony#1]
I need to return integer values for integers rather than strings. By using PDO::ATTR_EMULATE_PREPARES = false this works well:

`$connection = new PDO($dsn, $user, $pass, array(
    PDO::ATTR_EMULATE_PREPARES => false
))`

I am using this constructor in my Symfony 4.1 controller:
`public function __construct(Atlas $atlas)`

How can I add this attribute?

When I add it after line 57 in the pdo Connection it works great:

```    public function __construct(PDO $pdo)
    {
        $this->pdo = $pdo;
        $this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        $this->pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
    }
```

It seems to me that we should be able to get the connection objects from Atlas, alternatively be able to specify options when the connection is being set up. One alternative is to expand Factory::getPdoArgs to include the PDO options array so it can be specified in the .env file.

**Comment by pmjones** [comment]
> One alternative is to expand Factory::getPdoArgs to include the PDO options array so it can be specified in the .env file.

You are absolutely right. If you want to prepare a PR for that I will review it, otherwise I'll take care of it myself. Thanks!

**Comment by pokmot** [comment]
A good reason to learn; will create a PR in the next couple of days.

**Comment by pmjones** [comment]
In working through this, I am having trouble using PDO::CONSTANTS as Yaml keys in the config file. E.g. ...

```
    !php/const:PDO::ATTR_CASE: !php/const:PDO::CASE_NATURAL
```

... gets me "Notice: Uninitialized string offset" errors.

If you know how to make that work in Yaml, please tell me.

Otherwise, I may go with using string-literal representations of the constants ...

```
    'PDO::ATTR_CASE': 'PDO::CASE_NATURAL'
```

 and then use `constant()` to get the actual values in a loop in Factory::getPdoArgs().

**Comment by pmjones** [comment]
On further research, something like this might be useful: https://gist.github.com/samsch/d5243de3924a8ad10df2

So that all would be needed is for Factory::getPdoArgs() to look for a new 'options' key, a la:

```php
    protected static function getPdoArgs(array $spec) : array
    {
        return [
            $spec['dsn'] ?? null,
            $spec['username'] ?? null,
            $spec['password'] ?? null,
            $spec['options'] ?? null // <==
        ];
    }
```

Thoughts?

**Comment by pmjones** [comment]
Turns out I was using the wrong format for PHP constants in YAML. It should have been ...

```yaml
    !php/const PDO::ATTR_CASE: !php/const PDO::CASE_NATURAL
```

... which works fine. Working up the changes now!
